### PR TITLE
Send all requests through a Session instance with updated test cases

### PR DESCRIPTION
**Pull request by dojeda**
This is an updated version of the old PR https://github.com/pywebhdfs/pywebhdfs/pull/40 with updated test cases that use the `request.sessions.Session` object.

### CODE REVIEW

**Comment by dojeda** [comment]
@stevendgonzales @tarnfeld 
Hey guys, are you guys watching this PR? Do you have some time to take a look at it?

**Comment by stevendgonzales** [comment]
Looks good, thank you!

**Comment by tarnfeld** [comment]
Thanks again for taking this off my plate @dojeda! Glad to see this merged :)

**Comment by dojeda** [comment]
You are welcome! Thanks for looking into it!

**Pull request merged**
