### PR TITLE
add GETFILECHECKSUM support

### PR DESCRIPTION
**Pull request by choochootrain**

### CODE REVIEW

**Comment by stevendgonzales** [comment]
Thank you this s great, I will merge and get a new release out to Pypi soon

**Comment by choochootrain** [comment]
:+1: thanks!

**Comment by choochootrain** [comment]
bump, could you get this in a pypi release please?

**Comment by stevendgonzales** [comment]
done! https://pypi.python.org/pypi/pywebhdfs/0.3.2

**Pull request merged**
